### ISSUE TITLE
Padronização de style de código

### ISSUE THREAD

**Issue by digodk** [BitsPleaseBr/bits-please#60]
**Ideia ou etapa do projeto?**
Ideia

**Descreva o lance**
Elaborar um padrão de nomes de variáveis/métodos/classes/packages e deixar isso documentado na wiki

**Comentários adicionais**
**EXTREMAMENTE** importante, pois isso pode virar um problema logo e o código pode ficar deselegante!
Vamos conversar sobre isso em uma reunião em breve! Sem donos por enquanto.

**Comment by digodk** [comment]
Vou deixar aqui minha opinião para abrir esse assunto na reunião:
Sugiro eu e o @HillGus abordarmos elaborarmos um plano inicial e depois todos revisam.

**Comment by HillGus** [comment]
done
